<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <OutputType>Exe</OutputType>
      <WarningLevel>3</WarningLevel>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" />
      <PackageReference Include="Serilog" />
      <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>

</Project>
